# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QChat (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QChat (iOS)

end

target 'QChat (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QChat (macOS)

end
